---
- hosts: all
  remote_user: root
  tasks:
   - name: nano remove
     apt: name=nano state=absent
   - name: vim install
     apt: name=vim state=present   
   - name: nginx install
     apt: name=nginx state=present
     
   - name: curl install
     apt: name=curl state=present
     